// Generated by `pnpm --filter @brief/core find-pre-candidates`.
// Hand-edit between runs to add or remove specific candidates.
// Generated: 2026-05-11T15:56:23.834Z

export type Role = "digest" | "classify" | "vision";
export interface Candidate {
  provider: string;
  id: string;
}

export const preCandidates: Record<Role, Candidate[]> = {
  "digest": [
    {
      "provider": "google",
      "id": "gemini-3.1-flash-lite"
    },
    {
      "provider": "mistral",
      "id": "mistral-medium-2604"
    },
    {
      "provider": "nvidia",
      "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning"
    },
    {
      "provider": "deepseek",
      "id": "deepseek-v4-flash"
    },
    {
      "provider": "deepseek",
      "id": "deepseek-v4-pro"
    },
    {
      "provider": "togetherai",
      "id": "deepseek-ai/DeepSeek-V4-Pro"
    },
    {
      "provider": "openai",
      "id": "gpt-5.5"
    },
    {
      "provider": "openai",
      "id": "gpt-5.5-pro"
    },
    {
      "provider": "togetherai",
      "id": "moonshotai/Kimi-K2.6"
    },
    {
      "provider": "anthropic",
      "id": "claude-opus-4-7"
    },
    {
      "provider": "togetherai",
      "id": "zai-org/GLM-5.1"
    },
    {
      "provider": "google",
      "id": "gemma-4-31b-it"
    },
    {
      "provider": "nvidia",
      "id": "z-ai/glm-5.1"
    },
    {
      "provider": "togetherai",
      "id": "MiniMaxAI/MiniMax-M2.7"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4-mini"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4-nano"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-chat-latest"
    },
    {
      "provider": "nvidia",
      "id": "qwen/qwen3.5-122b-a10b"
    },
    {
      "provider": "anthropic",
      "id": "claude-sonnet-4-6"
    },
    {
      "provider": "nvidia",
      "id": "qwen/qwen3.5-397b-a17b"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-codex"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-codex-spark"
    },
    {
      "provider": "anthropic",
      "id": "claude-opus-4-6"
    },
    {
      "provider": "openai",
      "id": "gpt-5.2"
    }
  ],
  "classify": [
    {
      "provider": "google",
      "id": "gemini-3.1-flash-lite"
    },
    {
      "provider": "xai",
      "id": "grok-4.3"
    },
    {
      "provider": "mistral",
      "id": "mistral-medium-2604"
    },
    {
      "provider": "nvidia",
      "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning"
    },
    {
      "provider": "togetherai",
      "id": "moonshotai/Kimi-K2.6"
    },
    {
      "provider": "togetherai",
      "id": "google/gemma-4-31B-it"
    },
    {
      "provider": "nvidia",
      "id": "google/gemma-4-31b-it"
    },
    {
      "provider": "nvidia",
      "id": "nvidia/llama-nemotron-rerank-vl-1b-v2"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4-mini"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4-nano"
    },
    {
      "provider": "nvidia",
      "id": "nvidia/nemotron-voicechat"
    },
    {
      "provider": "mistral",
      "id": "mistral-small-latest"
    },
    {
      "provider": "xai",
      "id": "grok-4.20-0309-reasoning"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-chat-latest"
    },
    {
      "provider": "nvidia",
      "id": "qwen/qwen3.5-122b-a10b"
    },
    {
      "provider": "nvidia",
      "id": "qwen/qwen3.5-397b-a17b"
    },
    {
      "provider": "nvidia",
      "id": "nvidia/llama-nemotron-embed-vl-1b-v2"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-codex"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-codex-spark"
    },
    {
      "provider": "openai",
      "id": "gpt-5.2"
    },
    {
      "provider": "openai",
      "id": "gpt-5.2-codex"
    },
    {
      "provider": "nvidia",
      "id": "mistralai/devstral-2-123b-instruct-2512"
    },
    {
      "provider": "nvidia",
      "id": "mistralai/mistral-large-3-675b-instruct-2512"
    },
    {
      "provider": "deepseek",
      "id": "deepseek-chat"
    },
    {
      "provider": "deepseek",
      "id": "deepseek-reasoner"
    }
  ],
  "vision": [
    {
      "provider": "google",
      "id": "gemini-3.1-flash-lite"
    },
    {
      "provider": "xai",
      "id": "grok-4.3"
    },
    {
      "provider": "mistral",
      "id": "mistral-medium-2604"
    },
    {
      "provider": "nvidia",
      "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning"
    },
    {
      "provider": "openai",
      "id": "gpt-5.5"
    },
    {
      "provider": "openai",
      "id": "gpt-5.5-pro"
    },
    {
      "provider": "togetherai",
      "id": "moonshotai/Kimi-K2.6"
    },
    {
      "provider": "anthropic",
      "id": "claude-opus-4-7"
    },
    {
      "provider": "togetherai",
      "id": "google/gemma-4-31B-it"
    },
    {
      "provider": "nvidia",
      "id": "google/gemma-4-31b-it"
    },
    {
      "provider": "nvidia",
      "id": "nvidia/llama-nemotron-rerank-vl-1b-v2"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4-mini"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4-nano"
    },
    {
      "provider": "nvidia",
      "id": "nvidia/nemotron-voicechat"
    },
    {
      "provider": "mistral",
      "id": "mistral-small-latest"
    },
    {
      "provider": "xai",
      "id": "grok-4.20-0309-reasoning"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4-pro"
    },
    {
      "provider": "openai",
      "id": "gpt-5.4"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-chat-latest"
    },
    {
      "provider": "nvidia",
      "id": "qwen/qwen3.5-122b-a10b"
    },
    {
      "provider": "anthropic",
      "id": "claude-sonnet-4-6"
    },
    {
      "provider": "nvidia",
      "id": "qwen/qwen3.5-397b-a17b"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-codex"
    },
    {
      "provider": "openai",
      "id": "gpt-5.3-codex-spark"
    },
    {
      "provider": "anthropic",
      "id": "claude-opus-4-6"
    }
  ]
};
